<?php 

//-----------------------//
//remove me after include//
//-----------------------//

//include the db
require_once('Connections/dbDescent.php'); 

//initialize the session
if (!isset($_SESSION)) {
  session_start();
}

//include functions
include 'includes/function_logout.php';
include 'includes/function_getSQLValueString.php';

mysql_select_db($database_dbDescent, $dbDescent);

include 'includes/protected_page.php';

if (isset($_GET['urlGamingID'])) {
  $gameID = $_GET['urlGamingID'];
} else {
  header("Location: mycampaigns.php?view=all");
  die("Redirecting to mycampaigns.php");
}

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}


$query_rsGetCampaigns = sprintf("SELECT * FROM tbgames WHERE game_id = %s", GetSQLValueString($gameID, "int"));
$rsGetCampaigns = mysql_query($query_rsGetCampaigns, $dbDescent) or die(mysql_error());
$row_rsGetCampaigns = mysql_fetch_assoc($rsGetCampaigns);
$totalRows_rsGetCampaigns = mysql_num_rows($rsGetCampaigns);

if($row_rsGetCampaigns['game_dm'] != $_SESSION['user']['id']){
  header("Location: mycampaigns.php");
  die("Redirecting to mycampaigns.php");
} else {

  if ((isset($_POST["MM_insert"])) && ($_POST["MM_insert"] == "campaign-delete-form")) {

    mysql_select_db($database_dbDescent, $dbDescent);

    // Delete Travel
    $insertDeleteTravel = sprintf("DELETE FROM tbtravel_aquired WHERE travel_aq_game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteTravel = mysql_query($insertDeleteTravel, $dbDescent) or die(mysql_error());

    // Delete Skills
    $insertDeleteSkills = sprintf("DELETE FROM tbskills_aquired WHERE spendxp_game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteSkills = mysql_query($insertDeleteSkills, $dbDescent) or die(mysql_error());

    // Delete Items
    $insertDeleteItems = sprintf("DELETE FROM tbitems_aquired WHERE aq_game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteItems = mysql_query($insertDeleteItems, $dbDescent) or die(mysql_error());

    // Delete Progress
    $insertDeleteProgress = sprintf("DELETE FROM tbquests_progress WHERE progress_game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteProgress = mysql_query($insertDeleteProgress, $dbDescent) or die(mysql_error());

    // Delete Heroes
    $insertDeleteHeroes = sprintf("DELETE FROM tbcharacters WHERE char_game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteHeroes = mysql_query($insertDeleteHeroes, $dbDescent) or die(mysql_error());

    // Delete Game
    $insertDeleteGame = sprintf("DELETE FROM tbgames WHERE game_id = %s",
                        GetSQLValueString($gameID, "int"));

    $ResultDeleteGame = mysql_query($insertDeleteGame, $dbDescent) or die(mysql_error());

    header("Location: mycampaigns.php");
    die("Redirecting to mycampaigns.php"); 

  }

}

?>

<html>
  <head><?php 
    $pagetitle = "Delete Campaign";
    include 'head.php'; ?>
  </head>
  <body>

    <?php 
      include 'navbar.php'; 
      include 'banner.php';
    ?>

    

    <div class="container grey campaigns-overview">
      <form action="<?php echo $editFormAction; ?>" method="post" name="campaign-delete-form" id="campaign-delete-form">
        <div class="row no-gutters">
          <div class="col-sm-1">
          </div>
          <div class="col-sm-6 confirm-deco-text">
            <h1>Delete Campaign</h1>
            <p class="lead">Are you sure you want to delete this campaign? This cannot be undone.</p>
            <p class="">Statistics generated by this website are based on all existing campaigns on this website; for that reason, it would be best if you do not delete campaigns, even if they have been abandoned or completed</p>
            <input type="submit" class="btn large btn-primary" value="Delete" />
          </div>
          <div class="col-sm-1">
          </div>
          <div class="col-sm-3 confirm-deco">
            <img src="img/GoblinWitcher.png" />
          </div>
        </div>

        <input type="hidden" name="MM_insert" value="campaign-delete-form" />
      </form>
    </div>
  </body>
</html>
